### ISSUE TITLE
phpdcd 1.0.2 - undefined index

### ISSUE THREAD

**Issue by zdenekgebauer** [sebastianbergmann/phpdcd#45]
Notice: Undefined index: line in phar://C:/bin/phpdcd.phar/src/Analyser.php on l
ine 274

Call Stack:
    0.0063     369168   1. {main}() C:\bin\phpdcd.phar:0
    0.0301    1516264   2. Symfony\Component\Console\Application->run() C:\bin\p
hpdcd.phar:323
    0.0408    1903624   3. SebastianBergmann\PHPDCD\CLI\Application->doRun() pha
r://C:/bin/phpdcd.phar/symfony/console/Symfony/Component/Console/Application.php
:121
    0.0413    1904928   4. Symfony\Component\Console\Application->doRun() phar:/
/C:/bin/phpdcd.phar/src/CLI/Application.php:136
    0.0422    1905784   5. Symfony\Component\Console\Application->doRunCommand()
 phar://C:/bin/phpdcd.phar/symfony/console/Symfony/Component/Console/Application
.php:191
    0.0423    1906072   6. Symfony\Component\Console\Command\Command->run() phar
://C:/bin/phpdcd.phar/symfony/console/Symfony/Component/Console/Application.php:
892
    0.0446    1909016   7. SebastianBergmann\PHPDCD\CLI\Command->execute() phar:
//C:/bin/phpdcd.phar/symfony/console/Symfony/Component/Console/Command/Command.p
hp:241
    0.6098    2654096   8. SebastianBergmann\PHPDCD\Detector->detectDeadCode() p
har://C:/bin/phpdcd.phar/src/CLI/Command.php:137
    0.8881    5101736   9. SebastianBergmann\PHPDCD\Analyser->analyseFile() phar
://C:/bin/phpdcd.phar/src/Detector.php:69
    0.8886    5132168  10. SebastianBergmann\PHPDCD\Analyser->analyseSourceCode(
) phar://C:/bin/phpdcd.phar/src/Analyser.php:159

**Comment by shruthi-ananth** [comment]
This issue appears again in 1.0.2.

**Comment by DanielRuf** [comment]
+1

**Comment by jbenner-radham** [comment]
+1

**Comment by coelhoricardo** [comment]
+1

**Comment by ARACOOOL** [comment]
Version: 1.0.2
Notice: Undefined index: line in  sebastian\phpdcd\src\Analyser.php on line 238

**Comment by domhnallw** [comment]
I'm getting this too, but slightly different:

```
Notice: Undefined index:  in /home/vagrant/.composer/vendor/sebastian/phpdcd/src/Analyser.php on line 274
```

Running phpdcd 1.0.2 with PHP 5.5.30 on an Ubuntu 14.04 64-bit VM (host is a Macbook Pro running Virtualbox and Vagrant)

**Comment by sebastianbergmann** [comment]
I lost interest in this project a long time ago, mostly due to the [limitations](https://github.com/sebastianbergmann/phpdcd#limitations) of its implementation. Today I [added](https://github.com/sebastianbergmann/phpdcd/commit/69885271da311d3e849706306ae038f775d1ee99) a note that this project is no longer maintained to its documentation and closed all open tickets. Feel free to continue to work on this in a fork.
