### ISSUE TITLE
Installing on Windows

### ISSUE THREAD

**Issue by rebin** [sebastianbergmann/phpdcd#50]
When I install using composer and run phpdcd it shows

'phpdcd' is not recognized as an internal or external command,
operable program or batch file.

**Comment by kirktat** [comment]
Eternal-Infinity - First time user here....Thanks for the tip on how to execute phpdcd. 

Mr. Bergmann -

The only output I get when I execute phpdcd is for undefined index in the code, but no listing of dead functions. Where should I expect to find output that shows dead functions? Below is what I see.

Notice: Undefined index: line in phar://C:/phpdcd/phpdcd.phar/src/Analyser.php on line 274

Call Stack:
    0.0040     232320   1. {main}() C:\phpdcd\phpdcd.phar:0
    0.0170     980568   2. Symfony\Component\Console\Application->run() C:\phpdcd\phpdcd.phar:323
    0.0230    1233584   3. SebastianBergmann\PHPDCD\CLI\Application->doRun() phar://C:/phpdcd/phpdcd.phar/symfony/console/Symfony/Component/Console/Application.php:121
    0.0230    1234272   4. Symfony\Component\Console\Application->doRun() phar://C:/phpdcd/phpdcd.phar/src/CLI/Application.php:136
    0.0240    1234616   5. Symfony\Component\Console\Application->doRunCommand() phar://C:/phpdcd/phpdcd.phar/symfony/console/Symfony/Component/Console/Application.php:191
    0.0240    1234848   6. Symfony\Component\Console\Command\Command->run() phar://C:/phpdcd/phpdcd.phar/symfony/console/Symfony/Component/Console/Application.php:892
    0.0250    1237232   7. SebastianBergmann\PHPDCD\CLI\Command->execute() phar://C:/phpdcd/phpdcd.phar/symfony/console/Symfony/Component/Console/Command/Command.php:241
    0.4790    1734368   8. SebastianBergmann\PHPDCD\Detector->detectDeadCode() phar://C:/phpdcd/phpdcd.phar/src/CLI/Command.php:137
  157.4290   13547160   9. SebastianBergmann\PHPDCD\Analyser->analyseFile() phar://C:/phpdcd/phpdcd.phar/src/Detector.php:69
  157.4290   13644560  10. SebastianBergmann\PHPDCD\Analyser->analyseSourceCode() phar://C:/phpdcd/phpdcd.phar/src/Analyser.php:159

**Comment by sebastianbergmann** [comment]
I lost interest in this project a long time ago, mostly due to the [limitations](https://github.com/sebastianbergmann/phpdcd#limitations) of its implementation. Today I [added](https://github.com/sebastianbergmann/phpdcd/commit/69885271da311d3e849706306ae038f775d1ee99) a note that this project is no longer maintained to its documentation and closed all open tickets. Feel free to continue to work on this in a fork.
